[features]
seeds = false
skip-lint = false

[programs.localnet]
autocrat_v0 = "5QBbGKFSoL1hS4s5dsCBdNRVnJcMuHXFwhooKk2ar25S"
autocrat_v1 = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
clob = "Ap4Y89Jo1Xx7jtimjoWMGCPAKEgrarasU9iQ6Dc6Pxor"
conditional_vault = "4SrgFQyrvEYB3GupUaEjoULXCmzHCcAcTffHbpppycip"
twap_cpmm = "E4JnykRAH6FsFXeaKTyax3bBvPp8dnQXjcuFhakCQyth"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/clob.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000

[[test.genesis]]
address = "22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD"
program = "./dependencies/clob.so"
